### ISSUE TITLE
应该使用哪个数据集？

### ISSUE THREAD

**Issue by jin1ming** [chenjshnn/Object-Detection-for-Graphical-User-Interface#1]
您好，目前我在复现您论文中的一些数据，想请教下您Faster-RCNN和yolov3中的数据集不知道应该使用哪个。
Faster-RCNN中数据集有ricoCustomized、ricoDefault不太明白，yolov3中rico5box、rico也不太明白。您可以介绍下吗？

**Comment by chenjshnn** [comment]
Actually, different names mean different anchor box settings while training the model. They all use the same dataset, i.e., Rico.

These names correspond to Table 3.

** Anchor box setting (size & aspect ratio)**
Faster RCNN - Rico Customized: 32, 64, 128, 256, 512, 1:1, 2:1, 4:1, 8:1
Faster RCNN - Rico Default: 128, 256, 512, 1:1, 2:1, 4:1, 8:1
yolov3 - rico5box: use 5 anchor boxes, i.e., k=5
yolov3 - rico: use 9 anchor boxes, i.e., k=9
