### ISSUE TITLE
The train.txt, val.txt, test.txt files were not found. Can you upload these three files?

### ISSUE THREAD

**Issue by jin1ming** [chenjshnn/Object-Detection-for-Graphical-User-Interface#2]

**Comment by chenjshnn** [comment]
Please see the corresponding files in https://github.com/chenjshnn/Object-Detection-for-Graphical-User-Interface/tree/master/PyTorch-YOLOv3/data/rico 

For each file (train.txt/val.txt/test.txt), each line indicates one image path. You may need to change to your absolute/relative path

You could also find my splits in https://www.dropbox.com/sh/53rj0jjz74whxuq/AAAJ2WtTxmtgYvCu6xr8935ea?dl=0

**Comment by jin1ming** [comment]
Thanks.
