### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by illulachy** [chenjshnn/Object-Detection-for-Graphical-User-Interface#3]
Hi Chen,
I'm having trouble reproducing your results by running train.py with the rico dataset that I customized by myself but the results turn out not so good cuz the training loss always about 10.
Could you provide me the dataset that you customized.
Thanks in advance,
Regards

**Comment by chenjshnn** [comment]
Hi, 

This is my rico train/val/test dataset (without text elements). You can try to train the model on it to see if you can obtain a similar results. 
https://www.dropbox.com/sh/4higxc7e15abf1u/AACilquN6CZzadSymf44WAjGa?dl=0

Best,
Jieshan

**Comment by chenjshnn** [comment]
If you still have a similar problem, please feel free to post an issue and email me (jieshan.chen@anu.edu.au) as I did not check github frequently. I will normaly response in a week
