### ISSUE TITLE
Pretrained model weights.

### ISSUE THREAD

**Issue by meetgandhi123** [chenjshnn/Object-Detection-for-Graphical-User-Interface#4]
Mentioned in the Readme.md for several models that we need to place the pre-trained model weights in [Model_Directory]/result/run/[Dataset] folder. 

I wanted to know from where can we get the pre-trained model weights. 

For example, I want to run  PyTorch-YOLOv3 model with Roci dataset, can you please let me know from where should I download the weights of all models to place them into the PyTorch-YOLOv3/result/run/[DATASET] folder.

**Comment by chenjshnn** [comment]
Please find the trained models at https://www.dropbox.com/sh/xm1ssjkrqep3tah/AADwr4TAaVGak6wx57xuTVZsa?dl=0
